# Generated by Django 5.1.15 on 2026-04-27 00:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="SubjectGroup IDs to filter. Empty = all groups.",
                    ),
                ),
                (
                    "models_filter",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="ExamModel IDs to filter. Empty = all models.",
                    ),
                ),
                (
                    "problems",
                    models.JSONField(
                        default=list, help_text="Problem IDs this rule assigns correctors to."
                    ),
                ),
                (
                    "correctors",
                    models.JSONField(
                        default=list, help_text="User IDs of correctors assigned by this rule."
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_rules",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "rubric_selections",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of selected RubricCriterion IDs (rubric-based grading).",
                    ),
                ),
                (
                    "grader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grades_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["problem__order"],
            },
        ),
    ]
