# Generated by Django 5.1.15 on 2026-04-27 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        ("grading", "0001_initial"),
        ("instances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="instances.examinstance",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="problem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="exams.problem",
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("problem", "instance"), name="unique_grade_per_problem_instance"
            ),
        ),
    ]
