"""
Exam domain models.

Hierarchy:
    Subject → Exam → ExamModel → PageProfile → RecognitionZone
                                → Problem → RubricCriterion
              Exam → ExamConvocation (M2M with students)

Exam: A test within a subject (e.g. "Parcial 1 de Álgebra").
ExamModel: A structural variant (e.g. "A", "B") with its own blank PDF.
PageProfile: Per-page zone definitions within a model.
RecognitionZone: A typed rectangular region for recognition (QR, OCR, checkbox).
Problem: A graded section within a model, optionally linked to zones.
RubricCriterion: A checkmark criterion with fixed score for a problem.
ExamConvocation: Links an exam to its called students.

Key concepts:
    - Each model has a blank PDF and an instrumented PDF (with QR overlays).
    - `instrumented_pdf_valid` tracks whether the instrumented PDF is up-to-date.
    - Zones are typed: OCR_TEXT, OCR_NUMBER, QR, CHECKBOX — each uses a different
      recognizer during ingestion (Fase 6).
    - QR zones always have attribute='exam_qr' and encode org/exam/model/page.

References: RF-6.1 through RF-6.16
"""

from django.conf import settings
from django.db import models

from apps.core.models import OrganizationOwnedModel, TimestampedModel

# ── Enums ────────────────────────────────────────────────────


class ZoneType(models.TextChoices):
    """Type of recognition zone — determines which recognizer runs."""

    OCR_TEXT = "OCR_TEXT", "OCR Text (free text)"
    OCR_NUMBER = "OCR_NUMBER", "OCR Number (numeric)"
    QR = "QR", "QR Code"
    CHECKBOX = "CHECKBOX", "Checkbox (marked/unmarked)"


# Default student permissions on their exam instances (RF-6.10).
DEFAULT_STUDENT_PERMISSIONS = {
    "can_view_pages": True,
    "can_view_pages_after_review": False,
    "can_download_pages": False,
    "can_view_annotations": True,
    "can_view_rubric": True,
    "can_view_grade_breakdown": True,
}


# ── Exam ─────────────────────────────────────────────────────


class Exam(OrganizationOwnedModel):
    """A test within a subject (e.g. "Parcial 1 de Álgebra").

    Each exam has one or more models, a list of called students,
    and configurable student permissions.

    Attributes:
        name: Display name of the exam.
        subject: FK to the subject this exam belongs to.
        student_permissions: JSON dict controlling what students can
            see on their published instances (RF-6.10).
    """

    name = models.CharField(max_length=255)
    subject = models.ForeignKey(
        "subjects.Subject",
        on_delete=models.CASCADE,
        related_name="exams",
    )
    student_permissions = models.JSONField(
        default=dict,
        blank=True,
        help_text="Configurable student visibility on published instances.",
    )

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"{self.name} ({self.subject.code})"

    def save(self, *args, **kwargs):
        """Initialize default student permissions if empty."""
        if not self.student_permissions:
            self.student_permissions = dict(DEFAULT_STUDENT_PERMISSIONS)
        super().save(*args, **kwargs)


# ── ExamModel ────────────────────────────────────────────────


class ExamModel(TimestampedModel):
    """A structural variant of an exam (e.g. model "A", "B").

    Each model defines its own structure: page profiles with zones,
    problems, rubrics. Models within the same exam can share or
    differ in structure.

    The blank PDF is the original template. The instrumented PDF
    is generated by overlaying QR codes on the blank PDF.

    Attributes:
        label: Alphanumeric identifier (e.g. "A", "B", "C").
        exam: FK to the parent exam.
        blank_pdf_ref: MinIO object key for the blank PDF.
        blank_pdf_pages: Number of pages in the blank PDF.
        blank_pdf_size: File size in bytes.
        instrumented_pdf_ref: MinIO object key for the instrumented PDF.
        instrumented_pdf_valid: Whether the instrumented PDF is up-to-date.
            Set to False when blank PDF or QR zones change.
    """

    label = models.CharField(
        max_length=10,
        help_text="Alphanumeric model identifier (e.g. 'A', 'B').",
    )
    exam = models.ForeignKey(
        Exam,
        on_delete=models.CASCADE,
        related_name="models",
    )

    # Blank PDF metadata.
    blank_pdf_ref = models.CharField(
        max_length=500,
        blank=True,
        default="",
        help_text="MinIO object key for the blank PDF template.",
    )
    blank_pdf_pages = models.PositiveIntegerField(
        default=0,
        help_text="Number of pages in the blank PDF.",
    )
    blank_pdf_size = models.PositiveIntegerField(
        default=0,
        help_text="Blank PDF file size in bytes.",
    )

    # Instrumented PDF (with QR overlays).
    instrumented_pdf_ref = models.CharField(
        max_length=500,
        blank=True,
        default="",
        help_text="MinIO object key for the instrumented PDF.",
    )
    instrumented_pdf_valid = models.BooleanField(
        default=False,
        help_text="False when blank PDF or QR zones change; True after regeneration.",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["label", "exam"],
                name="unique_model_label_per_exam",
            ),
        ]
        ordering = ["label"]

    def __str__(self) -> str:
        return f"Model {self.label} ({self.exam.name})"

    def invalidate_instrumented_pdf(self) -> None:
        """Mark the instrumented PDF as needing regeneration."""
        if self.instrumented_pdf_valid:
            self.instrumented_pdf_valid = False
            self.save(update_fields=["instrumented_pdf_valid", "updated_at"])


# ── PageProfile & RecognitionZone ────────────────────────────


class PageProfile(TimestampedModel):
    """Groups recognition zones for a specific page within a model.

    Each PageProfile corresponds to one page of the blank PDF.
    It stores the page dimensions (from PDF metadata) used for
    coordinate validation.

    Attributes:
        exam_model: FK to the model this profile belongs to.
        page_number: 1-based page number within the PDF.
        page_width: Page width in PDF points (1pt = 1/72 inch).
        page_height: Page height in PDF points.
    """

    exam_model = models.ForeignKey(
        ExamModel,
        on_delete=models.CASCADE,
        related_name="page_profiles",
    )
    page_number = models.PositiveIntegerField(
        help_text="1-based page number within the blank PDF.",
    )
    page_width = models.FloatField(
        default=0.0,
        help_text="Page width in PDF points (1pt = 1/72 inch).",
    )
    page_height = models.FloatField(
        default=0.0,
        help_text="Page height in PDF points.",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["exam_model", "page_number"],
                name="unique_page_per_model",
            ),
        ]
        ordering = ["page_number"]

    def __str__(self) -> str:
        return f"Page {self.page_number} of Model {self.exam_model.label}"


class RecognitionZone(TimestampedModel):
    """A typed rectangular region on a page for recognition.

    Each zone has a type that determines which recognizer runs
    during ingestion (Fase 6):
    - OCR_TEXT: free text OCR (name, etc.)
    - OCR_NUMBER: numeric OCR with format validation
    - QR: QR code decoder (deterministic, no OCR engine)
    - CHECKBOX: binary mark detection

    QR zones always have attribute='exam_qr'. Their content
    encodes org_id, exam_id, model_id, page_number + checksum.

    Coordinates are in PDF points (absolute), with origin at
    bottom-left of the page (PDF standard).

    Attributes:
        page_profile: FK to the page this zone belongs to.
        zone_type: Type of recognition to apply.
        attribute: What this zone represents (name, dni, nia, exam_qr, etc.).
        x: X coordinate of the zone's bottom-left corner (PDF points).
        y: Y coordinate of the zone's bottom-left corner (PDF points).
        width: Zone width in PDF points.
        height: Zone height in PDF points.
    """

    page_profile = models.ForeignKey(
        PageProfile,
        on_delete=models.CASCADE,
        related_name="zones",
    )
    zone_type = models.CharField(
        max_length=20,
        choices=ZoneType.choices,
    )
    attribute = models.CharField(
        max_length=100,
        help_text="What this zone represents (e.g. 'name', 'dni', 'exam_qr').",
    )
    x = models.FloatField(help_text="X coordinate in PDF points (from left).")
    y = models.FloatField(help_text="Y coordinate in PDF points (from bottom).")
    width = models.FloatField(help_text="Zone width in PDF points.")
    height = models.FloatField(help_text="Zone height in PDF points.")

    class Meta:
        ordering = ["page_profile__page_number", "y", "x"]

    def __str__(self) -> str:
        return f"{self.zone_type}:{self.attribute} on page {self.page_profile.page_number}"

    def save(self, *args, **kwargs):
        """Force attribute='exam_qr' for QR zones."""
        if self.zone_type == ZoneType.QR:
            self.attribute = "exam_qr"
        super().save(*args, **kwargs)


# ── Problem & RubricCriterion ────────────────────────────────


class Problem(TimestampedModel):
    """A graded section within an exam model.

    Problems can optionally reference recognition zones that cover
    the answer region on the scanned page. A problem may have zero
    zones (free-form answer) or span multiple zones across pages.

    Attributes:
        name: Display name (e.g. "Problema 1", "Apartado a").
        max_score: Maximum points for this problem (can be negative for penalties).
        exam_model: FK to the model this problem belongs to.
        zones: Optional M2M to RecognitionZone for answer region references.
        order: Display order within the model.
    """

    name = models.CharField(max_length=255)
    max_score = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        help_text="Maximum score. Can be negative for penalty problems.",
    )
    exam_model = models.ForeignKey(
        ExamModel,
        on_delete=models.CASCADE,
        related_name="problems",
    )
    zones = models.ManyToManyField(
        RecognitionZone,
        blank=True,
        related_name="problems",
        help_text="Optional zones covering the answer region.",
    )
    order = models.PositiveIntegerField(
        default=0,
        help_text="Display order within the model.",
    )

    class Meta:
        ordering = ["order", "name"]

    def __str__(self) -> str:
        return f"{self.name} ({self.max_score}pts)"


class RubricCriterion(TimestampedModel):
    """A checkmark criterion with fixed score for a problem.

    Positive scores are normal criteria; negative scores are
    penalties. The sum of positive criteria should approximate
    the problem's max_score (not strictly enforced).

    Attributes:
        problem: FK to the problem this criterion belongs to.
        description: Text description of the criterion.
        score: Fixed score (positive or negative).
        order: Display order within the rubric.
    """

    problem = models.ForeignKey(
        Problem,
        on_delete=models.CASCADE,
        related_name="rubric_criteria",
    )
    description = models.TextField()
    score = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        help_text="Positive = points awarded, negative = penalty.",
    )
    order = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ["order"]

    def __str__(self) -> str:
        sign = "+" if self.score >= 0 else ""
        return f"{sign}{self.score}: {self.description[:50]}"


# ── ExamConvocation ──────────────────────────────────────────


class ExamConvocation(TimestampedModel):
    """Links an exam to a called student.

    Only students with an active SubjectMembership and an
    assigned group can be called (RF-6.4).

    Attributes:
        exam: FK to the exam.
        student: FK to the called student.
    """

    exam = models.ForeignKey(
        Exam,
        on_delete=models.CASCADE,
        related_name="convocations",
    )
    student = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="exam_convocations",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["exam", "student"],
                name="unique_convocation_per_exam",
            ),
        ]

    def __str__(self) -> str:
        return f"{self.student.email} → {self.exam.name}"
