# Generated by Django 5.1.15 on 2026-04-27 01:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        ("instances", "0002_alter_exampage_issue_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Rich text"),
                            ("STYLUS", "Stylus strokes (JSON)"),
                            ("AUDIO", "Audio recording"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "payload",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Inline content: rich text or JSON strokes. Empty for audio.",
                    ),
                ),
                (
                    "storage_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MinIO key for audio payloads.",
                        max_length=500,
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        default=1, help_text="1-based page number where the annotation is placed."
                    ),
                ),
                (
                    "x",
                    models.FloatField(
                        default=0.0, help_text="X coordinate on the page (percentage 0-100)."
                    ),
                ),
                (
                    "y",
                    models.FloatField(
                        default=0.0, help_text="Y coordinate on the page (percentage 0-100)."
                    ),
                ),
                (
                    "is_grade_annotation",
                    models.BooleanField(
                        default=False,
                        help_text="If True, OCR is triggered to extract a numeric grade.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="instances.examinstance",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional problem association. Null = general annotation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="annotations",
                        to="exams.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number", "y", "x"],
            },
        ),
    ]
