"""
Django settings for scdee project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/

This file contains settings shared across ALL environments (dev, prod).
Environment-specific overrides go in dev.py / prod.py.

Settings are grouped by concern and each group references the
requirement(s) it satisfies.
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# Read .env file if it exists (it won't in production containers
# where env vars are injected directly).
env_file = BASE_DIR / ".env"
if env_file.exists():
    env.read_env(str(env_file))

# ============================================================
# Core Django
# ============================================================
SECRET_KEY = env("DJANGO_SECRET_KEY")
DEBUG = env.bool("DJANGO_DEBUG", default=False)
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=[])

# ============================================================
# Applications
# ============================================================
# Order matters: Django apps first, then third-party, then ours.
# Our apps use the `apps.` prefix because they live under apps/.
DJANGO_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "corsheaders",
    "drf_spectacular",
    "django_celery_beat",
    "storages",
]

LOCAL_APPS = [
    "apps.core",
    "apps.audit",
    "apps.organizations",
    "apps.accounts",
    "apps.courses",
    "apps.subjects",
    "apps.exams",
    "apps.instances",
    "apps.grading",
    "apps.annotations",
    "apps.ingestion",
    "apps.reviews",
    "apps.notifications",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# ============================================================
# Middleware
# ============================================================
# Ordering is critical:
# 1. SecurityMiddleware first — adds security headers to every response
# 2. CorsMiddleware before CommonMiddleware — handles CORS preflight
# 3. TenantMiddleware after auth — needs authenticated user to resolve org
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    # CSRF deliberately omitted: this is a stateless JWT API with no
    # browser cookies. CSRF protection is irrelevant without session
    # cookies and would interfere with API clients. (RF-1.1)
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.core.middleware.OrganizationMiddleware",
]

ROOT_URLCONF = "scdee.urls"
WSGI_APPLICATION = "scdee.wsgi.application"
ASGI_APPLICATION = "scdee.asgi.application"

# No Django templates needed — this is a pure API backend.
TEMPLATES = []

# ============================================================
# Custom User model (RF-2, RNF-13)
# ============================================================
# MUST be set before the first migration. Changing it later requires
# a full database rebuild. We use AbstractBaseUser because our User
# has custom fields (encrypted DNI, NIA, organization FK) and custom
# semantics for is_staff (org manager, not Django admin).
AUTH_USER_MODEL = "accounts.User"


# ============================================================
# Database — PostgreSQL (RNF-3, RNF-13)
# ============================================================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME", default="scdee"),
        "USER": env("DB_USER", default="scdee"),
        "PASSWORD": env("DB_PASSWORD", default="scdee"),
        "HOST": env("DB_HOST", default="db"),
        "PORT": env.int("DB_PORT", default=5432),
        "ATOMIC_REQUESTS": True,
        # Use persistent connections to avoid TCP handshake per request.
        "CONN_MAX_AGE": env.int("DB_CONN_MAX_AGE", default=600),
        "OPTIONS": {
            # Force UTC for consistency regardless of server locale.
            "options": "-c timezone=UTC",
        },
    }
}

ATOMIC_REQUESTS = True
# wraps each HTTP request in a transaction.
# This ensures that if a view raises an exception mid-way, all DB
# changes roll back — critical for data integrity (RNF-13).

# Default PK type: UUID for all models that don't override it.
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ============================================================
# Cache — Redis (RNF-4)
# ============================================================
# Used for: organization config cache, token blacklist, general cache.
# NOT for primary data storage — only acceleration and ephemeral state.
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env("REDIS_URL", default="redis://redis:6379/0"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "TIMEOUT": 300,  # 5 minutes default TTL
    }
}

# ============================================================
# Password hashing (RF-16.4)
# ============================================================
# Argon2 is the winner of the Password Hashing Competition (2015).
# It's memory-hard, making GPU/ASIC brute-force attacks expensive.
# bcrypt is kept as fallback for password verification during migration.
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]

# ============================================================
# Django REST Framework (RNF-8, RNF-15)
# ============================================================
REST_FRAMEWORK = {
    # --- Authentication ---
    # JWT-based. No session auth, no basic auth.
    # The actual JWT backend will be implemented in Fase 1 (RF-1).
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    # --- Permissions ---
    # Default to requiring authentication on all endpoints.
    # Individual views can override with AllowAny where needed (e.g. health check).
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # --- Pagination (RNF-15) ---
    # Offset-based pagination as required by RNF-15.
    # Cursor-based would be more performant for large datasets, but the
    # requirements explicitly request offset pagination with total count.
    "DEFAULT_PAGINATION_CLASS": "apps.core.pagination.StandardPagination",
    "PAGE_SIZE": 25,
    # --- Error handling (RNF-8) ---
    # Custom exception handler that returns symbolic error codes
    # instead of human-readable messages, ensuring language independence.
    "EXCEPTION_HANDLER": "apps.core.exceptions.api_exception_handler",
    # --- Schema generation (RNF-8) ---
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # --- Content negotiation ---
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ],
    # --- Input validation ---
    # Strict: reject unknown fields to prevent silent data loss.
    "DEFAULT_FILTER_BACKENDS": [],
}

# ============================================================
# drf-spectacular — OpenAPI schema (RNF-8)
# ============================================================
SPECTACULAR_SETTINGS = {
    "TITLE": "SCDEE API",
    "DESCRIPTION": "Backend API for the Digital Exam Correction System",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # Use enum names instead of values for readability.
    "ENUM_NAME_OVERRIDES": {},
    # Component naming: avoid collisions between apps.
    "COMPONENT_SPLIT_REQUEST": True,
}

# ============================================================
# Celery — async task queue (RNF-4)
# ============================================================
# Three separate queues for workload isolation:
# - default: general tasks
# - ocr: CPU-intensive OCR processing (RF-9)
# - notifications: email sending (RF-13)
# This separation ensures slow OCR tasks don't block email delivery.
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://redis:6379/1")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://redis:6379/2")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 300  # 5 min hard kill
CELERY_TASK_SOFT_TIME_LIMIT = 240  # 4 min graceful timeout
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_QUEUES = {
    "default": {},
    "ocr": {},
    "notifications": {},
}
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# ============================================================
# Object storage — MinIO / S3 (RNF-14)
# ============================================================
# MinIO is S3-compatible, so we use django-storages with the S3 backend.
# Shared bucket with per-organization prefixes for simplicity in v1.0.
AWS_ACCESS_KEY_ID = env("MINIO_ACCESS_KEY", default="minioadmin")
AWS_SECRET_ACCESS_KEY = env("MINIO_SECRET_KEY", default="minioadmin")
AWS_STORAGE_BUCKET_NAME = env("MINIO_BUCKET_NAME", default="scdee")
AWS_S3_ENDPOINT_URL = env("MINIO_ENDPOINT_URL", default="http://minio:9000")
AWS_S3_REGION_NAME = env("MINIO_REGION", default="us-east-1")
AWS_S3_FILE_OVERWRITE = False  # Never silently overwrite existing files
AWS_DEFAULT_ACL = None  # Use bucket default ACL
AWS_QUERYSTRING_AUTH = True  # Generate presigned URLs (RF-16.5)
AWS_S3_SIGNATURE_VERSION = "s3v4"
# Presigned URL expiration (seconds). Configurable per-org in OrganizationConfig.
AWS_PRESIGNED_URL_EXPIRY = env.int("AWS_PRESIGNED_URL_EXPIRY", default=900)

# ============================================================
# Email (RF-13, RF-2.7)
# ============================================================
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST", default="mailpit")
EMAIL_PORT = env.int("EMAIL_PORT", default=1025)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="noreply@scdee.local")

# ============================================================
# Internationalization (RNF-10)
# ============================================================
# The API itself is language-agnostic (symbolic error codes in English).
# i18n is used for email templates and notification messages.
LANGUAGE_CODE = "es"
LANGUAGES = [
    ("es", "Español"),
    ("en", "English"),
]
LOCALE_PATHS = [
    BASE_DIR / "locale",
]
USE_I18N = True
USE_L10N = True
TIME_ZONE = "UTC"
USE_TZ = True  # Always store datetimes in UTC

# ============================================================
# Security headers (RNF-6)
# ============================================================
# These headers protect against common web attacks even in an API context,
# because browsers may still interpret API responses in unexpected ways
# (e.g. if a user navigates directly to an API URL).

# Prevent MIME sniffing — browser must trust the Content-Type header.
SECURE_CONTENT_TYPE_NOSNIFF = True

# Prevent embedding in iframes — stops clickjacking attacks.
X_FRAME_OPTIONS = "DENY"

# Control what URL information is sent in the Referer header.
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Disable cross-site-scripting filter (modern browsers use CSP instead,
# and this header can introduce vulnerabilities in some edge cases).
SECURE_BROWSER_XSS_FILTER = False

# ============================================================
# CORS (RNF-6)
# ============================================================
# Configured via env var so each environment can specify its own origins.
# In production, this should be the exact frontend domain(s).
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=["http://localhost:3000"],
)
CORS_ALLOW_CREDENTIALS = False  # No cookies — JWT in Authorization header
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "origin",
    "x-requested-with",
]

# ============================================================
# Encryption (RF-16.3)
# ============================================================
# Master key for AES-256-GCM encryption of sensitive fields (DNI).
# Stored as hex-encoded string, never in the database.
ENCRYPTION_MASTER_KEY = env("ENCRYPTION_MASTER_KEY")

# ============================================================
# JWT Configuration (RF-1.2, RF-1.3)
# ============================================================
JWT_ACCESS_TOKEN_LIFETIME_MINUTES = env.int("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", default=15)
JWT_REFRESH_TOKEN_LIFETIME_DAYS = env.int("JWT_REFRESH_TOKEN_LIFETIME_DAYS", default=7)
JWT_ALGORITHM = "HS256"

# ============================================================
# Logging — structured JSON (RNF-11)
# ============================================================
# Two independent log streams:
# 1. Application log: technical events (errors, warnings, debug).
#    Rotated periodically, standard severity levels.
# 2. Audit log: business events with data impact.
#    Immutable, stored in PostgreSQL, never deleted.
LOG_LEVEL = env("LOG_LEVEL", default="INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "apps.core.logging.JsonFormatter",
        },
        "simple": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "celery": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "apps": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# ============================================================
# Ingestion — SFTP / filesystem watcher (RF-9.1)
# ============================================================
# In development, we use a local directory instead of a real SFTP server.
INGESTION_WATCH_DIR = env(
    "INGESTION_WATCH_DIR",
    default=str(BASE_DIR / "ingestion_inbox"),
)
# Max PDF size in MB (RF-15.1, default overridable per-organization)
MAX_PDF_SIZE_MB = env.int("MAX_PDF_SIZE_MB", default=50)

# ============================================================
# Static files (only for Swagger UI / ReDoc)
# ============================================================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
