# Generated by Django 5.1.15 on 2026-05-08 05:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("GRADES_PUBLISHED", "Grades published"),
                            ("REVIEW_OPENED", "Review window opened"),
                            ("REVIEW_RESULT", "Review result available"),
                            ("REVIEW_REQUESTS_SUMMARY", "Review requests summary"),
                            ("ASSIGNMENT_CREATED", "Grading assignment created"),
                            ("INGESTION_ISSUE", "Ingestion issue detected"),
                            ("COURSE_TRANSITION", "Course transition completed"),
                            ("DELETION_REMINDER", "Automatic deletion reminder"),
                            ("GENERAL", "General notification"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("UNREAD", "Unread"), ("READ", "Read"), ("ARCHIVED", "Archived")],
                        db_index=True,
                        default="UNREAD",
                        max_length=10,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra context data (exam name, counts, etc.).",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="For course-based archival during transitions.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="courses.academiccourse",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "-created_at"], name="idx_notif_user_status"
                    )
                ],
            },
        ),
    ]
