"""
RF-16.7 access-control tests for student PDF downloads.

RF-16.7 mandates **temporary URLs with short expiration and simple
encryption of the PDF in transit, derived from the user's session
identifier**, plus the cessation of access once the review window
closes. The current implementation:

- Composes the PDF on each request from MinIO and streams the bytes
  through the Django view (``InstanceDownloadView``). MinIO presigned
  URLs are generated by ``apps.exams.services.storage.generate_presigned_url``
  but are only used for the manager's instrumented-PDF download —
  the student flow never sees them.
- Does not encrypt the PDF in transit beyond TLS at the edge.
- Does not check the instance's status nor the exam's
  ``student_permissions.can_view_pages_after_review`` when the
  student fetches their own PDF.

References: RF-16.7, RF-12.x.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime, timedelta
from decimal import Decimal

import pytest
from django.contrib.auth import get_user_model
from django.test import override_settings
from rest_framework.test import APIClient

from apps.accounts.authentication import reset_auth_plugin
from apps.courses.models.courses import AcademicCourse
from apps.exams.models.exams import Exam, ExamModel, Problem
from apps.instances.models.instances import ExamInstance, ExamPage, InstanceStatus, PageStatus
from apps.organizations.models.organization import Organization
from apps.reviews.models.reviews import ExamReview, ReviewStatus
from apps.subjects.models.subjects import MembershipRole, Subject, SubjectMembership

pytestmark = [pytest.mark.django_db, pytest.mark.integration]
VALID_KEY = "a" * 64


# ── Fixtures and helpers ───────────────────────────────────────────


@pytest.fixture(autouse=True)
def _stub_jwt_blacklist(monkeypatch):
    """Bypass Redis-backed JWT calls in test (LocMemCache only)."""
    monkeypatch.setattr(
        "apps.accounts.blacklist.get_user_token_generation",
        lambda user_id: 0,
    )
    monkeypatch.setattr(
        "apps.accounts.blacklist.is_blacklisted",
        lambda jti: False,
    )


@pytest.fixture(autouse=True)
def _stub_compose(monkeypatch):
    """Stub PDF composition so we don't need MinIO for these tests."""
    monkeypatch.setattr(
        "apps.instances.services.instance_service.compose_instance_pdf",
        lambda instance, watermark_for_student=False: b"%PDF-1.4\n%fake\n%%EOF",
    )


def _login(email: str, password: str) -> APIClient:
    reset_auth_plugin()
    client = APIClient()
    response = client.post(
        "/api/v1/auth/login/",
        {"email": email, "password": password},
        format="json",
    )
    assert response.status_code == 200
    client.credentials(HTTP_AUTHORIZATION=f"Bearer {response.data['access_token']}")
    return client


def _setup_exam_and_student():
    """Build org + exam + 1 student + 1 instance owned by them."""
    user_model = get_user_model()
    suffix = uuid.uuid4().hex[:8]

    org = Organization.objects.create(name=f"Org-{suffix}", subdomain=f"o{suffix}")
    coordinator = user_model.objects.create_user(
        email=f"c-{suffix}@x.com",
        password="P@ss123!",  # noqa: S106
        first_name="C",
        last_name="O",
        organization=org,
        is_staff=True,
    )
    course = AcademicCourse.objects.create(organization=org, label="2026", is_active=True)
    subject = Subject.objects.create(
        organization=org,
        name="S",
        code=f"S{suffix}",
        course=course,
        coordinator=coordinator,
    )
    SubjectMembership.objects.create(
        organization=org,
        user=coordinator,
        subject=subject,
        role=MembershipRole.COORDINATOR,
        is_active=True,
    )
    exam = Exam.objects.create(organization=org, name="E", subject=subject)
    model = ExamModel.objects.create(label="A", exam=exam)
    Problem.objects.create(name="P1", max_score=Decimal("10.00"), exam_model=model, order=1)

    student = user_model.objects.create_user(
        email=f"s-{suffix}@x.com",
        password="StuPass123!",  # noqa: S106
        first_name="Stu",
        last_name="Dent",
        organization=org,
    )
    SubjectMembership.objects.create(
        organization=org,
        user=student,
        subject=subject,
        role=MembershipRole.STUDENT,
        is_active=True,
    )

    instance = ExamInstance.objects.create(
        organization=org,
        exam=exam,
        model=model,
        student=student,
        status=InstanceStatus.PUBLISHED,
        expected_pages=1,
    )
    ExamPage.objects.create(
        instance=instance,
        page_number=1,
        storage_ref="fake/ref",
        status=PageStatus.RECOGNIZED,
    )

    return {
        "org": org,
        "exam": exam,
        "student": student,
        "student_pw": "StuPass123!",
        "instance": instance,
    }


# ── Tests ──────────────────────────────────────────────────────────


@override_settings(ENCRYPTION_MASTER_KEY=VALID_KEY)
def test_student_cannot_download_after_review_finalized_when_not_allowed():
    """When ``can_view_pages_after_review=False`` and the instance is
    FINALIZED, the student must receive 403 / 404, not the PDF.
    """
    setup = _setup_exam_and_student()
    instance = setup["instance"]
    exam = setup["exam"]

    # Lock down post-review access at the exam level.
    exam.student_permissions = dict(exam.student_permissions or {})
    exam.student_permissions["can_view_pages_after_review"] = False
    exam.save()

    # Move the instance to FINALIZED (review window closed, no requests).
    instance.status = InstanceStatus.FINALIZED
    instance.save()

    client = _login(setup["student"].email, setup["student_pw"])
    response = client.get(f"/api/v1/instances/{instance.pk}/download/")

    # Expected (RF-16.7): 403 or 404 — no PDF.
    assert response.status_code in {403, 404}, (
        f"Student must NOT be able to download PDF after review closes "
        f"with can_view_pages_after_review=False. Got "
        f"{response.status_code}; response was a {response.get('Content-Type')!r}."
    )


@override_settings(ENCRYPTION_MASTER_KEY=VALID_KEY)
def test_student_pdf_response_is_encrypted_in_transit():
    """The PDF served to the student must be wrapped in an envelope
    keyed off the user's session identifier (RF-16.7).

    A simple acceptance criterion: the response body must NOT begin
    with ``%PDF-`` (the unencrypted PDF magic) when the consumer is a
    student. Today it does.
    """
    setup = _setup_exam_and_student()
    ExamReview.objects.create(
        exam=setup["exam"],
        start_date=datetime.now(tz=UTC) - timedelta(hours=1),
        end_date=datetime.now(tz=UTC) + timedelta(days=2),
        status=ReviewStatus.OPEN,
    )
    setup["instance"].status = InstanceStatus.IN_REVIEW
    setup["instance"].save()
    client = _login(setup["student"].email, setup["student_pw"])
    response = client.get(f"/api/v1/instances/{setup['instance'].pk}/download/")

    assert response.status_code == 200
    assert not response.content.startswith(b"%PDF-"), (
        "Student PDF body starts with the plain-text PDF magic — there "
        "is no in-transit encryption envelope (RF-16.7)."
    )


@override_settings(ENCRYPTION_MASTER_KEY=VALID_KEY)
def test_pdf_download_blocked_when_review_completed_and_policy_disallows():
    """ExamReview.status == COMPLETED + ``can_view_pages_after_review=False``
    must result in 403/404 for student downloads.
    """
    from datetime import UTC, datetime, timedelta

    setup = _setup_exam_and_student()
    instance = setup["instance"]
    exam = setup["exam"]

    # Disallow post-review viewing.
    exam.student_permissions = dict(exam.student_permissions or {})
    exam.student_permissions["can_view_pages_after_review"] = False
    exam.save()

    # Create a COMPLETED review for the exam.
    now = datetime.now(tz=UTC)
    ExamReview.objects.create(
        exam=exam,
        start_date=now - timedelta(days=14),
        end_date=now - timedelta(days=7),
        status=ReviewStatus.COMPLETED,
    )
    instance.status = InstanceStatus.FINALIZED
    instance.save()

    client = _login(setup["student"].email, setup["student_pw"])
    response = client.get(f"/api/v1/instances/{instance.pk}/download/")
    assert response.status_code in {403, 404}, (
        f"Student got the PDF after the review window closed and policy "
        f"says no post-review viewing. Got {response.status_code}."
    )
