# Generated by Django 5.1.15 on 2026-05-08 05:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "student_permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configurable student visibility on published instances.",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(blank=True, help_text="Date of the exam", null=True),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text="Alphanumeric model identifier (e.g. 'A', 'B').", max_length=10
                    ),
                ),
                (
                    "blank_pdf_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="MinIO object key for the blank PDF template.",
                        max_length=500,
                    ),
                ),
                (
                    "blank_pdf_pages",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of pages in the blank PDF."
                    ),
                ),
                (
                    "blank_pdf_size",
                    models.PositiveIntegerField(
                        default=0, help_text="Blank PDF file size in bytes."
                    ),
                ),
                (
                    "page_dimensions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Cached page dimensions from the last blank PDF upload. List of {'page': int, 'width': float, 'height': float}.",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="PageProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        help_text="1-based page number within the blank PDF."
                    ),
                ),
                (
                    "page_width",
                    models.FloatField(
                        default=0.0, help_text="Page width in PDF points (1pt = 1/72 inch)."
                    ),
                ),
                (
                    "page_height",
                    models.FloatField(default=0.0, help_text="Page height in PDF points."),
                ),
                (
                    "exam_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_profiles",
                        to="exams.exammodel",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number"],
            },
        ),
        migrations.CreateModel(
            name="RecognitionZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("OCR_TEXT", "OCR Text (free text)"),
                            ("OCR_NUMBER", "OCR Number (numeric)"),
                            ("QR", "QR Code"),
                            ("CHECKBOX", "Checkbox (marked/unmarked)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "attribute",
                    models.CharField(
                        help_text="What this zone represents (e.g. 'name', 'dni', 'exam_qr').",
                        max_length=100,
                    ),
                ),
                ("x", models.FloatField(help_text="X coordinate in PDF points (from left).")),
                ("y", models.FloatField(help_text="Y coordinate in PDF points (from bottom).")),
                ("width", models.FloatField(help_text="Zone width in PDF points.")),
                ("height", models.FloatField(help_text="Zone height in PDF points.")),
                (
                    "page_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="exams.pageprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["page_profile__page_number", "y", "x"],
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum score. Can be negative for penalty problems.",
                        max_digits=6,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within the model."
                    ),
                ),
                (
                    "exam_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="exams.exammodel",
                    ),
                ),
                (
                    "zones",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optional zones covering the answer region.",
                        related_name="problems",
                        to="exams.recognitionzone",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RubricCriterion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive = points awarded, negative = penalty.",
                        max_digits=6,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubric_criteria",
                        to="exams.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExamConvocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="convocations",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_convocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exam", "student"), name="unique_convocation_per_exam"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="exammodel",
            constraint=models.UniqueConstraint(
                fields=("label", "exam"), name="unique_model_label_per_exam"
            ),
        ),
        migrations.AddConstraint(
            model_name="pageprofile",
            constraint=models.UniqueConstraint(
                fields=("exam_model", "page_number"), name="unique_page_per_model"
            ),
        ),
    ]
