# Generated by Django 5.1.15 on 2026-05-08 05:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OidcConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "client_secret",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stored encrypted. Decrypted at runtime.",
                        max_length=500,
                    ),
                ),
                (
                    "discovery_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="OIDC discovery endpoint (.well-known/openid-configuration).",
                    ),
                ),
                ("authorization_url", models.URLField(blank=True, default="")),
                ("token_url", models.URLField(blank=True, default="")),
                ("userinfo_url", models.URLField(blank=True, default="")),
                (
                    "attribute_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Mapping of OIDC claims to user fields.",
                    ),
                ),
                (
                    "scopes",
                    models.CharField(blank=True, default="openid email profile", max_length=255),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oidc_config",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "OIDC Configuration",
            },
        ),
        migrations.CreateModel(
            name="SamlConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="IdP entity ID (from IdP metadata).",
                        max_length=500,
                    ),
                ),
                (
                    "sso_url",
                    models.URLField(
                        blank=True, default="", help_text="IdP Single Sign-On service URL."
                    ),
                ),
                (
                    "slo_url",
                    models.URLField(
                        blank=True, default="", help_text="IdP Single Logout service URL."
                    ),
                ),
                (
                    "x509_cert",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="IdP X.509 certificate for signature validation.",
                    ),
                ),
                (
                    "attribute_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Mapping of SAML attributes to user fields. E.g. {"email": "urn:oid:..."}',
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saml_config",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "SAML Configuration",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("nia", models.CharField(blank=True, default="", max_length=50)),
                ("encrypted_dni", models.BinaryField(blank=True, null=True)),
                ("dni_nonce", models.BinaryField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive users cannot authenticate (soft delete)."
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Organization manager: can manage users, courses, config.",
                    ),
                ),
                (
                    "is_superadmin",
                    models.BooleanField(
                        default=False,
                        help_text="System-level admin: can create/manage organizations.",
                    ),
                ),
                ("email_notifications_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null only for system superadmins without an org.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(fields=["organization", "is_active"], name="idx_user_org_active")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("email", "organization"), name="unique_email_per_organization"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("nia", ""), _negated=True),
                        fields=("nia", "organization"),
                        name="unique_nia_per_organization",
                    ),
                ],
            },
        ),
    ]
