# Generated by Django 5.1.15 on 2026-04-27 01:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("organizations", "0002_organizationconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="OidcConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "client_secret",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stored encrypted. Decrypted at runtime.",
                        max_length=500,
                    ),
                ),
                (
                    "discovery_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="OIDC discovery endpoint (.well-known/openid-configuration).",
                    ),
                ),
                ("authorization_url", models.URLField(blank=True, default="")),
                ("token_url", models.URLField(blank=True, default="")),
                ("userinfo_url", models.URLField(blank=True, default="")),
                (
                    "attribute_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Mapping of OIDC claims to user fields.",
                    ),
                ),
                (
                    "scopes",
                    models.CharField(blank=True, default="openid email profile", max_length=255),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oidc_config",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "OIDC Configuration",
            },
        ),
        migrations.CreateModel(
            name="SamlConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="IdP entity ID (from IdP metadata).",
                        max_length=500,
                    ),
                ),
                (
                    "sso_url",
                    models.URLField(
                        blank=True, default="", help_text="IdP Single Sign-On service URL."
                    ),
                ),
                (
                    "slo_url",
                    models.URLField(
                        blank=True, default="", help_text="IdP Single Logout service URL."
                    ),
                ),
                (
                    "x509_cert",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="IdP X.509 certificate for signature validation.",
                    ),
                ),
                (
                    "attribute_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Mapping of SAML attributes to user fields. E.g. {"email": "urn:oid:..."}',
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saml_config",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "SAML Configuration",
            },
        ),
    ]
