# Generated by Django 5.1.15 on 2026-04-26 23:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code within the course (e.g. 'EDA').", max_length=50
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-form period label (e.g. '1er cuatrimestre').",
                        max_length=100,
                    ),
                ),
                (
                    "coordinator",
                    models.ForeignKey(
                        help_text="User who coordinates this subject.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coordinated_subjects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The academic course this subject belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_set",
                        to="courses.academiccourse",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubjectGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text="Alphanumeric group identifier (e.g. 'G1', '2121').",
                        max_length=50,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="SubjectMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("COORDINATOR", "Coordinator"),
                            ("TEACHER", "Teacher"),
                            ("STUDENT", "Student"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "permission_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-user permission overrides. Empty = use role defaults.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Group assignment. Null = no group assigned.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships",
                        to="subjects.subjectgroup",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="subjects.subject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("code", "course"), name="unique_subject_code_per_course"
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectgroup",
            constraint=models.UniqueConstraint(
                fields=("label", "subject"), name="unique_group_label_per_subject"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectmembership",
            index=models.Index(
                fields=["subject", "role", "is_active"], name="idx_membership_subject_role"
            ),
        ),
        migrations.AddIndex(
            model_name="subjectmembership",
            index=models.Index(fields=["user", "is_active"], name="idx_membership_user_active"),
        ),
        migrations.AddConstraint(
            model_name="subjectmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user", "subject"),
                name="unique_active_membership_per_subject",
            ),
        ),
    ]
