# Generated by Django 5.1.15 on 2026-05-08 05:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        ("instances", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateTimeField(help_text="When the review window opens.")),
                ("end_date", models.DateTimeField(help_text="When the review window closes.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled (not yet open)"),
                            ("OPEN", "Open (students can submit requests)"),
                            ("CLOSED", "Closed (requests being processed)"),
                            ("COMPLETED", "Completed (all requests resolved)"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=15,
                    ),
                ),
                (
                    "notify_students",
                    models.BooleanField(
                        default=True, help_text="Whether students were notified about this review."
                    ),
                ),
                (
                    "exam",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_message",
                    models.TextField(
                        blank=True, default="", help_text="Student's reason for requesting review."
                    ),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolver_message",
                    models.TextField(
                        blank=True, default="", help_text="Corrector's response to the student."
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_requests",
                        to="instances.examinstance",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_requests",
                        to="exams.problem",
                    ),
                ),
                (
                    "resolver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="reviews.examreview",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("instance", "problem"), name="unique_review_request_per_problem"
                    )
                ],
            },
        ),
    ]
