# Generated by Django 5.1.15 on 2026-05-08 05:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ASSEMBLING", "Assembling pages"),
                            ("RECEIVED", "All pages received"),
                            ("QUEUED", "Queued for recognition"),
                            ("PENDING_GRADING", "Pending grading"),
                            ("GRADED", "Graded"),
                            ("PUBLISHED", "Published to student"),
                            ("IN_REVIEW", "In review period"),
                            ("PENDING_REVIEW", "Pending review resolution"),
                            ("FINALIZED", "Finalized"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="ASSEMBLING",
                        max_length=20,
                    ),
                ),
                ("has_issues", models.BooleanField(db_index=True, default=False)),
                (
                    "issue_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of active instance-level issue type strings.",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Computed sum of grades (min 0). Null if not yet graded.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "expected_pages",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of expected pages based on model's PageProfiles.",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="exams.exam",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances",
                        to="exams.exammodel",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="organizations.organization",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_instances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        default=0, help_text="1-based order within the instance."
                    ),
                ),
                (
                    "storage_ref",
                    models.CharField(
                        help_text="MinIO object key for the scanned image.", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_RECOGNITION", "Pending recognition"),
                            ("RECOGNIZED", "Recognition complete"),
                            ("ORPHAN", "Orphan (no QR, assigned by proximity)"),
                            ("DISCARDED", "Discarded by coordinator"),
                        ],
                        db_index=True,
                        default="PENDING_RECOGNITION",
                        max_length=25,
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("QR_READ_ERROR", "QR code could not be decoded"),
                            ("QR_MISMATCH", "QR indicates different exam/model/page"),
                            ("ORPHAN_PAGE", "Page assigned by temporal proximity"),
                            ("EXTRA_PAGE", "Page number exceeds expected count"),
                        ],
                        default="",
                        help_text="Page-level issue type, if any.",
                        max_length=25,
                    ),
                ),
                ("recognized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="instances.examinstance",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orphan_pages",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["page_number"],
            },
        ),
        migrations.AddIndex(
            model_name="examinstance",
            index=models.Index(fields=["exam", "status"], name="idx_instance_exam_status"),
        ),
        migrations.AddConstraint(
            model_name="examinstance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("student__isnull", False)),
                fields=("exam", "student"),
                name="unique_student_per_exam",
            ),
        ),
    ]
