# Generated by Django 5.1.15 on 2026-05-16 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0001_initial"),
        ("instances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exampage",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                help_text="Batch this page arrived with (e.g. a multi-page PDF upload).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pages",
                to="ingestion.ingestionbatch",
            ),
        ),
        migrations.AddField(
            model_name="exampage",
            name="recognized_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Result of zone recognition: {zones: [...], qr_payload: {...}}",
            ),
        ),
    ]
