# Generated by Django 5.1.15 on 2026-04-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instances", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exampage",
            name="issue_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("QR_READ_ERROR", "QR code could not be decoded"),
                    ("QR_MISMATCH", "QR indicates different exam/model/page"),
                    ("ORPHAN_PAGE", "Page assigned by temporal proximity"),
                    ("EXTRA_PAGE", "Page number exceeds expected count"),
                ],
                default="",
                help_text="Page-level issue type, if any.",
                max_length=25,
            ),
        ),
    ]
