# Generated by Django 5.1.15 on 2026-05-01 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instances", "0002_alter_exampage_issue_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examinstance",
            name="version",
        ),
    ]
