# Generated by Django 5.1.15 on 2026-05-16 23:21

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionBatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("watcher", "SFTP Watcher"), ("manual", "Manual upload")],
                        default="watcher",
                        max_length=20,
                    ),
                ),
                (
                    "student_id",
                    models.UUIDField(
                        blank=True,
                        help_text="If known in advance (e.g. professor uploads a student's exam).",
                        null=True,
                    ),
                ),
                ("total_pages", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_batches",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
