# Generated by Django 5.1.15 on 2026-05-18 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingestionbatch",
            name="organization",
        ),
    ]
