# Generated by Django 5.1.15 on 2026-04-08 23:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "subdomain",
                    models.CharField(
                        db_index=True,
                        help_text="Unique subdomain identifier for URL routing.",
                        max_length=63,
                        unique=True,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[("FREE", "Free"), ("PREMIUM", "Premium")],
                        default="FREE",
                        max_length=20,
                    ),
                ),
                (
                    "auth_mode",
                    models.CharField(
                        choices=[("JWT", "JWT Credentials")], default="JWT", max_length=20
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
