# Generated by Django 5.1.15 on 2026-04-27 01:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_ocr_engine",
                    models.CharField(
                        default="easyocr",
                        help_text="OCR engine ID (easyocr, tesseract).",
                        max_length=50,
                    ),
                ),
                (
                    "recognition_confidence_threshold",
                    models.FloatField(
                        default=0.7, help_text="Minimum confidence for auto-accepting OCR results."
                    ),
                ),
                (
                    "assembly_timeout_seconds",
                    models.IntegerField(
                        default=600,
                        help_text="Seconds before marking ASSEMBLING instances as MISSING_PAGE.",
                    ),
                ),
                (
                    "orphan_proximity_threshold_seconds",
                    models.IntegerField(
                        default=30,
                        help_text="Temporal proximity window for orphan page assignment.",
                    ),
                ),
                (
                    "max_audio_duration_minutes",
                    models.IntegerField(
                        default=60, help_text="Maximum audio annotation duration in minutes."
                    ),
                ),
                (
                    "max_page_size_mb",
                    models.IntegerField(default=50, help_text="Maximum page image size in MB."),
                ),
                (
                    "auto_delete_frequency_days",
                    models.IntegerField(
                        default=365,
                        help_text="Days after course archival before automatic deletion.",
                    ),
                ),
                (
                    "delete_notice_days",
                    models.IntegerField(
                        default=30, help_text="Days before deletion to notify managers."
                    ),
                ),
                (
                    "default_language",
                    models.CharField(
                        default="es",
                        help_text="Default language for emails and notifications.",
                        max_length=5,
                    ),
                ),
                (
                    "temp_url_expiration_minutes",
                    models.IntegerField(
                        default=15, help_text="Expiration time for MinIO presigned URLs."
                    ),
                ),
                (
                    "role_permission_defaults",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-role permission defaults override. Empty = use code defaults.",
                    ),
                ),
                (
                    "grade_export_columns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='CSV column order for grade export. Empty = default ["nia","name","group","grade"].',
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Configuration",
            },
        ),
    ]
