# Generated by Django 5.1.15 on 2026-04-27 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_organizationconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationconfig",
            name="orphan_proximity_threshold_seconds",
        ),
    ]
